name: Publish

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.20.3
            - name: Use Node.js 16
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: 'pnpm'
            - run: echo '\n//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
            - run: pnpm install
            - run: pnpm build
            - run: pnpm publish
